name: Terraform CI/CD Pipeline

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to (e.g., dev, staging, prod)"
        required: true
        type: string
      aws-assume-role-arn:
        description: "The ARN of the AWS IAM Role to assume for deployment"
        required: true
        type: string
      aws-region:
        description: "The AWS region to deploy to"
        required: true
        type: string
      aws-statefile-s3-bucket:
        description: "The S3 bucket to store Terraform state files"
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
    
      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          aws-region: ${{ inputs.aws-region }}
          role-session-name: "TerraformDeploymentSession"

      - name: Read Destroy Config
        id: read-destroy-config
        run: |
          DESTROY="$(jq -r '.${{ inputs.environment }}' ./infra/destroy-config.json)"
          echo "destroy=$(echo $DESTROY)" >> $GITHUB_OUTPUT
          echo "Destroy flag for environment '${{ inputs.environment }}': $DESTROY"

      - name: "Initialize Terraform"
        id: terraform-init
        run: |
          cd infra && terraform init \
          -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
          -backend-config="key=statefile/terraform.tfstate" \
          -backend-config="region=${{ inputs.aws-region }}" \
          -backend-config="use_lockfile=true"
      
      - name: Terraform Validate
        id: terraform-validate
        run: |
          cd infra && terraform validate

      - name: Terraform Destroy
        id: terraform-destroy
        if: steps.read-destroy-config.outputs.destroy == 'true'
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform destroy -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -auto-approve

      - name: Terraform Plan
        if: steps.read-destroy-config.outputs.destroy != 'true'
        id: terraform-plan
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -out="${{ inputs.environment }}.tfplan"

      - name: Terraform Apply
        if: steps.read-destroy-config.outputs.destroy != 'true'
        id: terraform-apply
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.tfplan"
